### ISSUE TITLE
Poetry caching fails because Poetry is not installed

### ISSUE THREAD

**Issue by nwjsmith** [actions/setup-python#369]
**Description:**
Poetry caching fails because Poetry is not installed.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
All Python versions.

**Repro steps:**  
Run a workflow with the `setup-python` action using the `cache: 'poetry'` argument. I have set up [a minimal reproduction in a public repository](https://github.com/nwjsmith/poetry-caching-repro). There is an example of [a failed workflow run in that project](https://github.com/nwjsmith/poetry-caching-repro/runs/5792380266?check_suite_focus=true).

**Expected behavior:**
I would expect Poetry dependencies to be restored if they exist.

**Actual behavior:**
The step fails due to a missing `poetry` executable.

**Comment by dmitry-shibanov** [comment]
Hello @nwjsmith. Thank you for your report. It's an expected behaviour because the setup-python action uses poetry to get its [configuration](https://github.com/actions/setup-python/blob/main/src/cache-distributions/poetry-cache.ts#L44-L73). Poetry should be preinstalled before using the setup-python action.

For now I'm going to close the issue.

**Comment by tony** [comment]
The reason I'm not filing a separate is I think it'd be closed on the same grounds as this issue.

But I'd like to note my workaround for python versions and poetry 1.x to work:

It looks like installing `poetry` before `actions/setup-python` causes `poetry` to use the earlier python version. e.g. if GH uses python 3.8 by default and poetry is installed in that, your poetry is going to run in 3.8, no matter what `actions/setup-python` is.

It looks like `poetry install` doesn't obey the python version that actions/setup-python uses.

Here's an example
- https://github.com/vcs-python/libvcs/runs/5801763507?check_suite_focus=true
  
  ![image](https://user-images.githubusercontent.com/26336/161400385-f390943a-87c0-44e0-a583-33fd2274a055.png)
- https://github.com/vcs-python/libvcs/blob/f2798b8d4e5199a88d16118f2ade74b328e860f6/.github/workflows/tests.yml

- It also happens when installing via `pipx install poetry`

My workaround is to use a matrix and `poetry env <version>`

```yaml
name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version 1.1.12
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          rm install-poetry.py

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          # This is required to do as of @actions/checkout@v3 to prevent default action python (3.8) from being used
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: Lint with flake8
        run: poetry run flake8

      - name: Print python versions
        run: |
          python -V
          poetry run python -V

      - name: Test with pytest
        run: poetry run py.test
```

You can replace "Install poetry` with `pipx install poetry`, or `pipx install poetry==1.1.12`, etc.

**Comment by dmitry-shibanov** [comment]
Hello @tony. Thank you for your report. I'll reopen the issue for deeper investigation.

**Comment by tony** [comment]
@dmitry-shibanov I created an independent issue here: https://github.com/actions/setup-python/issues/374

**Comment by dmitry-shibanov** [comment]
Hello everyone. For now I'm going to close the issue because we released a new version with fix and updated major tag.

**Comment by jirojo2** [comment]
Doesn't work for me as of today @4.2.0

**Comment by luisroel91** [comment]
This isn't fixed...the error still occurs as of today

**Comment by dunossauro** [comment]
Same issue here. Using version 4.5.0

**Comment by luisroel91** [comment]
@dmitry-shibanov this issue is not fixed...any chance we can re-open this issue?

**Comment by khvn26** [comment]
Sorry for a meaningless +1, but just bumped into this. Hoping to see this fixed!

**Comment by EvanShaw** [comment]
This should be reopened. The docs also still indicate that poetry must be installed before using this action: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

I think it goes without saying, but until this gets resolved, python being a prerequisite of poetry renders the use of this action pretty much pointless

**Comment by eduardoklosowski** [comment]
In all runners images there is already a relatively recent version of python 3 pre-installed ([Included Software column](https://github.com/actions/runner-images#available-images)), which can be used without problems to install poetry (except for Ubuntu 18.04 which will be discontinued), and python installed by setup-python after poetry is recognized normally when the virtual env is created, which doesn't cause any problems. I think that if it is not done in this sequence, setup-python would need to install poetry too, and why should it install poetry and not other options like pipenv, hatch, pdm...? Does it make sense for setup-python to have options to install these tools as well, or should it just focus on python?

And if you really need to install poetry on a specific version of python, you can use setup-python without use the cache options, install poetry, and call [actions/cache](https://github.com/actions/cache) directly afterward.

**Comment by EvanShaw** [comment]
I don't know about other people's use cases, but consider this scenario:

- install a specific version of python with this action
- create a virtualenv (eg: `python3 -m venv .venv`)
- install poetry through the virtualenv (`.venv/bin/pip install poetry`)
- install packages with poetry (`.venv/bin/poetry install`)

In this scenario, using the cache option will fail because poetry doesn't exist, but why does poetry need to exist before the cache is even accessed? It hasn't installed any packages yet

**Comment by eduardoklosowski** [comment]
> In this scenario, using the cache option will fail because poetry doesn't exist, but why does poetry need to exist before the cache is even accessed? It hasn't installed any packages yet

@EvanShaw because this action run `poetry config --list` ([source](https://github.com/actions/setup-python/blob/7b9ef6fc5a7a74dfb7c0924eb42615d7af1e4de5/src/cache-distributions/poetry-cache.ts#L87)) to know how poetry is configured and which directory should be cached. Otherwise the poetry configuration could be changed and the cache would not work properly either.

**Comment by telia-tomsan** [comment]
I would like to advocate for the dependency on poetry to be removed. I'm trying to get this working on my company's own test runners but it's a pain, pip isn't preinstalled so I can't simply install poetry like in the examples.

**Comment by adam-grant-hendry** [comment]
> Hello @nwjsmith. Thank you for your report. It's an expected behaviour because the setup-python action uses poetry to get its [configuration](https://github.com/actions/setup-python/blob/main/src/cache-distributions/poetry-cache.ts#L44-L73). Poetry should be preinstalled before using the setup-python action.

`poetry` is installed with `python` or `pipx` (which also requires `python`) except on MacOS where `brew` can be used, so it's often not possible to first install `poetry` (see [#659](https://github.com/actions/setup-python/issues/659#issuecomment-1721964826)).

The action should therefore install `poetry` after setting up python and configure the cache.

**Comment by adam-grant-hendry** [comment]
> poetry is installed with python or pipx (which also requires python) except on MacOS where brew can be used, so it's often not possible to first install poetry (see https://github.com/actions/setup-python/issues/659#issuecomment-1721964826).

Oops, I forgot about [pre-installed software on each runner](There is a "cart before the horse" issue here depending on the OS.), and they all have a python version. My mistake...

**Comment by hejfelix** [comment]
this is still an issue. Reopen? it is very counter intuitive to assume `pipx` is installed before I run the setup-python action – let alone that I need to install poetry before setting up python.

**Comment by ruqiabegumm** [comment]
It seems the issue you are encountering is related to the absence of the Poetry executable during the caching step. When using the setup-python action with the cache: 'poetry' argument, the workflow expects Poetry to be pre-installed to restore dependencies.

To address this, ensure that Poetry is explicitly installed as part of your workflow setup before attempting to cache dependencies. You can add a step to install Poetry using pip install poetry or leverage a dedicated action for Poetry setup.

Meanwhile, if you're in the mood for some reflective moments, take a break and explore [Sad Shayari in Hindi](https://sadshayri.net/), a soothing collection for those emotional breaks between debugging sessions.

Example Fix:
Here’s a quick example of how you could modify your workflow to ensure Poetry is available:

yaml
Copy code
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install Poetry
        run: pip install poetry
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Dependencies
        run: poetry install
This should ensure that Poetry is installed and available when the caching step is executed, preventing the failure you described.

For a more heartfelt collection of poetic content, explore [Emotional Sad Shayari](https://sadshayri.net/300-emotional-sad-shayari-in-hindi/) – it might provide some comfort during those tough debugging moments.
