### ISSUE TITLE
v3.1's default poetry example uses wrong python version

### ISSUE THREAD

**Issue by tony** [actions/setup-python#374]
**Description:**

The default configuration example for #281's new example installs poetry _before_ `actions/setup-python` is ran.

This can run into some funky issues in poetry itself since poetry may stick to use the python version it was installed in.

This may be on the poetry side. I'm not sure:
- Oldest post I could find (closed): https://github.com/python-poetry/poetry/issues/655
- https://github.com/python-poetry/poetry/issues/4101
- ~~See if in 1.2.x prerelease PR helps: https://github.com/python-poetry/poetry/pull/4852~~: Seems not to https://github.com/tony/setup-python-poetry-version-example/blob/main/.github/workflows/experiment-with-poetry-prerelease.yml

**Action version:**
v3.1

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
Reproduction repo: https://github.com/tony/setup-python-poetry-version-example

- https://github.com/tony/setup-python-poetry-version-example/tree/main/.github/workflows

  - [default-example.yml](https://github.com/tony/setup-python-poetry-version-example/blob/main/.github/workflows/default-example.yml)
  - [default-example-install-poetry.yml](https://github.com/tony/setup-python-poetry-version-example/blob/main/.github/workflows/default-example-install-poetry.yml)
  - [experiment-with-poetry-prerelease.yml](https://github.com/tony/setup-python-poetry-version-example/blob/main/.github/workflows/experiment-with-poetry-prerelease.yml)
  - [workaround.yml](https://github.com/tony/setup-python-poetry-version-example/blob/main/.github/workflows/workaround.yml) by trigger `poetry env use <version>` to force version

Runs: https://github.com/tony/setup-python-poetry-version-example/actions

**Expected behavior:**
`poetry` should respect the version in `actions/setup-python`

**Actual behavior:**
It uses the python version `poetry` was installed with before `actions/setup-python` was ran.

**Comment by matthew-mcallister** [comment]
How hard would it be to defer caching to a later step? Then you wouldn't have to rely on the system version of Python. I'm thinking something like this:
```yaml
- name: Install Python
  uses: actions/setup-python@v3
  with:  # Install Python, skip caching
    python-version: ${{ matrix.python-version }}
- name: Install poetry
  run: python -m pip install poetry
- name: Cache Poetry deps
  uses: actions/setup-python@v3
  with:  # Restore cache, skip Python installation
    cache: poetry
```

**Comment by dhvcc** [comment]
@matthew-mcallister this action [relies](https://github.com/actions/setup-python/blob/main/src/cache-distributions/poetry-cache.ts) on poetry to tell it's config values. The problem with locking poetry onto 1 version can be solved by installing poetry with curl. This action wil help you https://github.com/snok/install-poetry. However, take note, that it's significantly slower than `pipx install poetry`

**Comment by falkben** [comment]
You can get around this problem by telling `poetry` to use the same version of python as installed by `setup-python` with the `poetry env use` command

This has been working for me:

```yml
- uses: actions/checkout@v3

- name: Install poetry
  run: pipx install poetry

- name: Setup Python
  uses: actions/setup-python@v3
  with:
    python-version: "3.10"
    cache: "poetry"

- name: Install dependencies
  run: |
    poetry env use "3.10"
    poetry install --no-interaction
```

**Comment by dogweather** [comment]
Really weird: I do **not** get this error on a feature branch / PR:

![Screen Shot 2022-04-10 at 1 25 53 PM](https://user-images.githubusercontent.com/150670/162637052-399eb629-26ab-45c6-8d1b-63271d4125fd.png)

But I do get the wrong Python version after merged to `master`:

![Screen Shot 2022-04-10 at 1 25 28 PM](https://user-images.githubusercontent.com/150670/162637073-151350aa-6da8-48ea-bd35-19e631213f12.png)

**Comment by dogweather** [comment]
@falkben Your recipe works for me **if** I disable caching. Otherwise, it still uses the wrong Python. I introduced caching in the latest PR. I'm thinking I might need to delete the cache for some reason.

**Comment by dogweather** [comment]
Well, I can't find a way to delete the cache, so I've disabled it for now, and the correct Python is used again on `master`.

**Comment by dhvcc** [comment]
@dogweather, for me it seems like poetry's ignoring your `poetry env use` because it thinks that your're already using this env (since config/env values are retrieved from cache). While this behaviour is ok, the strange part is why does it execute the wrong version in the end

**Comment by shelper** [comment]
same for windows, see #425 
and the workaround here does not work 'cus `poetry env use 3.x` does not work, see https://github.com/python-poetry/poetry/issues/2117

**Comment by IvanZosimov** [comment]
Hello, everyone 👋 It's a well-known [issue](https://github.com/python-poetry/poetry/issues/655) of the poetry. Poetry tends to use the system's version of the python. Workarounds from the comments below can be helpful.

**Comment by psychobolt** [comment]
> You can get around this problem by telling `poetry` to use the same version of python as installed by `setup-python` with the `poetry env use` command
> 
> This has been working for me:
> 
> ```yaml
> - uses: actions/checkout@v3
> 
> - name: Install poetry
>   run: pipx install poetry
> 
> - name: Setup Python
>   uses: actions/setup-python@v3
>   with:
>     python-version: "3.10"
>     cache: "poetry"
> 
> - name: Install dependencies
>   run: |
>     poetry env use "3.10"
>     poetry install --no-interaction
> ```

Also works with `system` after setup-python e.g.
```yml
- uses: actions/setup-python@v3
   with:
      python-version: 3.x
      cache: poetry
- run: poetry env use system
   shell: bash
```

**Comment by IvanZosimov** [comment]
Hi, @psychobolt 👋 ! Thanks for the comment. but in that case, poetry just writes that it uses python 3.10.5, in fact, it proceeds to use 3.8.10 and because of that, your workflow can be failed later.

**Comment by dmitry-shibanov** [comment]
Hello everyone. Sorry for the late response. We released a new version of the action and updated the major tag with possible fix. Could you please confirm that everything works as expected.

**Comment by Tenzer** [comment]
I can confirm the latest version (4.2.0) fixes the problem in the places I've previously had to add the `poetry env use 3.10` workaround. Thanks!

**Comment by dmitry-shibanov** [comment]
Hello @Tenzer. Thank you for your response. For now I'm going to close the issue.

**Comment by omBratteng** [comment]
I encountered this issue as well, and spent some time trying to figure out why this was still happening after upgrading the action to v4.2.0.
It is cache, it had the wrong python version cached.

To solve it, I used the GitHub API to get a list of caches, and then delete it. Once done, I re-ran the workflow, and it rebuilt the cache and had the correct python version.

**Comment by omBratteng** [comment]
> > To solve it, I used the GitHub API to get a list of caches, and then delete it.
> 
> How did you delete it? Where did you delete it from?

First I ran this, to get a list of the caches, in this case, there was only one.
 ```shell
gh api \
  -H "Accept: application/vnd.github+json" \
  /repos/OWNER/REPO/actions/caches
```

Then I ran this, to delete the cache, based off of the cache ID in the previous command.
```shell

gh api \
  --method DELETE \
  -H "Accept: application/vnd.github+json" \
  /repos/OWNER/REPO/actions/caches/CACHE_ID
```

More information available here: https://docs.github.com/en/rest/actions/cache
