### ISSUE TITLE
Specifying x86 (32-bit) pypy-nightly on Windows installs a 64-bit binary

### ISSUE THREAD

**Issue by alex** [actions/setup-python#518]
**Description:**

```
      - name: Setup python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "pypy-3.8-nightly"
          architecture: "x86"
```

**Action version:**

4.2.0

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

pypy-3.8-nightly, pypy-3.9-nightly

**Repro steps:**  

Use the action specified above. Look at the output and see:

```
Downloading PyPy from "https://buildbot.pypy.org/nightly/py3.8/pypy-c-jit-latest-win64.zip" ...
```

**Expected behavior:**

A 32-bit binary is installed.

**Actual behavior:**
A 64-bit binary!

**Comment by nulano** [comment]
> Expected behavior:
> A 32-bit binary is installed.

There is no 32-bit Windows build of recent PyPy versions since PyPy 7.3.4.

> Actual behavior:
> A 64-bit binary!

Whether this action should fail or silently switch to 64-bit is a separate question, related to https://github.com/actions/setup-python/pull/168#issuecomment-747634851 and https://github.com/actions/setup-python/pull/201.

**Comment by alex** [comment]
Hmm, indeed. I think this should be an error then, its very confusing to request one thing and get another -- in my case it produces confusing linker errors later on.

**Comment by vsafonkin** [comment]
Hi @alex, we will take a look at this, thank you for your report.

**Comment by vsafonkin** [comment]
Hi @alex, i've merged [this PR](https://github.com/actions/setup-python/pull/520) to fix it. It's available via `setup-python@main` at the moment and will be available via tag after release a new version of `setup-python` action.

**Comment by alex** [comment]
great, thanks!

**Comment by vsafonkin** [comment]
I'm going to close this issue, feel free to contact us if you have any concerns, thank you!

**Comment by graingert** [comment]
> Hi @alex, i've merged [this PR](https://github.com/actions/setup-python/pull/520) to fix it. It's available via `setup-python@main` at the moment and will be available via version tag after a new release of `setup-python` action.

It looks like this wasn't fixed, specifying architecture: x86 still installs the x64 version rather than raising an error
