### ISSUE TITLE
Python 3.7 recently broken (no _bz2 module) on macOS 13

### ISSUE THREAD

**Issue by gsnedders** [actions/setup-python#682]
### Description

Recently (i.e., since last week), we've started seeing a number of Python 3.7 tasks failing with:

```
../manifest/download.py:2: in <module>
    import bz2
/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/bz2.py:19: in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
E   ModuleNotFoundError: No module named '_bz2'
```

Presumably something in the new image caused CPython to fail to compile the _bz2 module?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230611.2

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=102338&view=logs&jobId=cd4b0752-91ac-5ee3-1416-93dd445ec171&j=5eb1b5a9-6d44-5065-06d8-b95593136516&t=2324b04f-e597-4527-9bcd-b3f55a7684b6

### Is it regression?

20230524.1

### Expected behavior

The Python 3.7 `_bz2` module to be installed.

### Actual behavior

The Python 3.7 `_bz2` module is not installed.

### Repro steps

`python3.7 -c 'import bz2'`

**Comment by mikhailkoliada** [comment]
Transferring to setup-python as they are responsible for tool cached python 

CC @dmitry-shibanov @MaksimZhukov

**Comment by MaksimZhukov** [comment]
Hello @gsnedders! Thank you for reporting this! 
We will investigate the issue!

**Comment by AlexWaygood** [comment]
We're also hitting this at typeshed, where we're using Python 3.7 on macOS 11 -- see https://github.com/python/typeshed/issues/10333 for a list of some recent failing runs.

**Comment by ihnorton** [comment]
Please also consider setting `export MACOSX_DEPLOYMENT_TARGET=10.15`, because (inter alia) the current build leads to errors when building wheels for 3.7 or 3.8 with a deployment target earlier than version of the build machine for the python binary:
```
2023-06-23T05:32:23.9559420Z error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.15" but "11.7" during configure
```

(this doesn't happen with the 3.9+ binaries because the issue was fixed in setuptools/distutils AFAICT; see eg https://bugzilla.mozilla.org/show_bug.cgi?id=659881 and related links from there)

**Comment by parafoxia** [comment]
Hi @dmitry-shibanov, just ran my pipeline against the newest 3.7 build, and it still failed in the same way.

Here's the logs should you wish to view them: https://github.com/parafoxia/analytix/actions/runs/5358039214/jobs/9719771048

**Comment by parafoxia** [comment]
Hi @dmitry-shibanov, ran the workflow your code, and it works! Apologies for the duplicate notification, I didn't run it with the cache removal step the first time round.

**Comment by dmitry-shibanov** [comment]
Thank you for your response @parafoxia. I'll keep the issue opened until the hosted runners are updated.

**Comment by seanlaw** [comment]
> Thank you for your response @parafoxia. I'll keep the issue opened until the hosted runners are updated.

@dmitry-shibanov Any idea when the hosted runners might be updated and available?

**Comment by dmitry-shibanov** [comment]
Hello @seanlaw. I think it should be uploaded at the end of this week.

**Comment by seanlaw** [comment]
> Hello everyone. We uploaded a new version of python 3.7.17 with the fix. Could you please try to use this snippet to confirm that it works as expected?
> 
> ```yaml
>       - run: rm -rf $RUNNER_TOOL_CACHE/Python/3.7.17
>       - uses: actions/setup-python@v4
>         with:
>           python-version: 3.7.17
> ```

@dmitry-shibanov I would also like to confirm that this worked for me as well.

**Comment by macanudo527** [comment]
@dmitry-shibanov  It seems like the hosted runners have been updated. Tests are passing without the added snippet.
