### ISSUE TITLE
Caching does not work when using an internal package repo

### ISSUE THREAD

**Issue by screig** [actions/setup-python#984]
**Description:**
The caching feature wont work if one is pip installing from another python package repository. 

**Action version:**
actions/setup-python@v5

**Platform:**
- [X ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X ] Hosted
- [ ] Self-hosted
Current runner version: '2.321.0'
Runner Image
  Image: ubuntu-22.04
  Version: 20241201.1.0

**Tools version:**
I think it applies across Python versions

**Repro steps:**  
The code is on our internal repo so I can share a link, here is the yaml

First we set up Python, and specify that we wish to cache.

```
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements*.txt
```

Next I install two sets of requirements

```
      - name: Install dependencies f
        run: |
          echo "Python version is : ${{ matrix.python-version }}"
          pip --version
          pip install -r requirements_for_testing.txt        
          pip install -r requirements.txt --extra-index-url https://${ado_token}@OUR_INETERNAL_ADO_PACKAGE REPO/_packaging/sepypi/pypi/simple/
          pip --version
          pip list

```

requirements_for_testing.txt contains packages that we can get from pypi. Now here the caching works fine.

![image](https://github.com/user-attachments/assets/dd8f92d8-5562-48fd-8197-531852a1fe7f)

Next we need to install requirements that include our internal packages on our internal ADO package repo.

`     pip install -r requirements.txt --extra-index-url https://${ado_token}@OUR_INETERNAL_ADO_PACKAGE REPO/_packaging/sepypi/pypi/simple/`

Here the caching never works.

![image](https://github.com/user-attachments/assets/82eaf6f6-a5a2-4324-9f6f-2a0688bd28ed)

**Expected behaviour:**
I would expect it to cache.

**Actual behaviour:**
Its not caching...

**Comment by jommeke22f** [comment]
> **Beschrijving:** De cache functie werkt niet als pip wordt geïnstalleerd vanuit een andere Psychopathologie.
> 
> **Actievere:** actions/setup-python@voor
> 
> **Platform:**
> 
> * [X] Ubuntu-versie
> * [ ] macOS
> * [ ] Vensters
> 
> **Type loper:**
> 
> * [X ] Gehost
> * [ ] Zelf gehost 
>   Huidige runner-versie: '2.321.0' 
>   Runner-afbeelding 
>   Afbeelding: ubuntu-22.04 
>   Versie: 20241201.1.0
> 
> **Tools-versie:** Ik denk dat het van toepassing is op alle Python-versies
> 
> **Repro stappen:** De code staat in onze interne repository, dus ik kan een link delen, hier is de yam
> 
> Eerst stellen we Python in en geven aan dat we willen cachen.
> 
> ```
>       - uses: actions/setup-python@vele
>         with:
>           python-version: '3.9'
>           cache: 'pip'
>           cache-dependency-path: requirements*.txt
> ```
> 
> Vervolgens installeer ik twee sets vereisten
> 
> ```
>       - name: Install dependencies f
>         run: |
>           echo "Python version is : ${{ matrix.python-version }}"
>           pip --version
>           pip install -r requirements_for_testing.txt        
>           pip install -r requirements.txt --extra-index-url https://${ado_token}@OUR_INETERNAL_ADO_PACKAGE REPO/_packaging/Seppe/Pipi/simple/
>           pip --version
>           pip list
> ```
> 
> requirements_for_testing.txt bevat pakketten die we van papier kunnen krijgen. Hier werkt de caching prima.
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/4292074/395607430-dd8f92d8-5562-48fd-8197-531852a1fe7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzUwNDcsIm5iZiI6MTczNDI3NDc0NywicGF0aCI6Ii80MjkyMDc0LzM5NTYwNzQzMC1kZDhmOTJkOC01NTYyLTQ4ZmQtODE5Ny01MzE4NTJhMWZlN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTVUMTQ1OTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E4NTU3OWI2MDFlMGY2NjcxN2EyMGQ1MzIyMjg0MDRiZjE0ZmZjMjNmOWU3MDZiYzQyOTYzYjliYTkxYmM4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fQMLqBsFqtVNV9k1Yy_SqMlnnk4uGPAI9nPyGfgy_dY)
> 
> Vervolgens moeten we de vereisten installeren die onze interne pakketten bevatten in onze interne Doktersassistente.
> 
> ` pip install -r requirements.txt --extra-index-url https://${ado_token}@OUR_INETERNAL_ADO_PACKAGE REPO/_packaging/Seppe/ppi/simple/`
> 
> Hier werkt de caching nooit.
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/4292074/395608377-82eaf6f6-a5a2-4324-9f6f-2a0688bd28ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzUwNDcsIm5iZiI6MTczNDI3NDc0NywicGF0aCI6Ii80MjkyMDc0LzM5NTYwODM3Ny04MmVhZjZmNi1hNWEyLTQzMjQtOWY2Zi0yYTA2ODhiZDI4ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTVUMTQ1OTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlhZDUyNmUzNjg4MTZjNjllZGIyMTAzOTZlNWJkNWNkOGU5Njg1NDI3ZTMwNmIyMDkxOTYzMTg4MDEwYWM5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.r7mssT78shpDRl0pppFD2tbZ7va6zkQnLvKNzWtT96U)
> 
> **Verwacht gedrag:** Ik verwacht dat het cachet.
> 
> **Actueel gedrag:** Er wordt niet gecached...

**Comment by lmvysakh** [comment]
Hy, After investigating we found the following issues were causing the caching to fail, such as secret handling, syntax error in the  "pip install -r requirements.txt --extra-index-url https://${ado_token}@OUR_INETERNAL_ADO_PACKAGE REPO/_packaging/sepypi/pypi/simple/" which was an invalid format for pip install.

So, the initial fix was made in the following way:

pip install -r requirements.txt --extra-index-url https://${{secrets.ado_token}}@OUR_INETERNAL_ADO_PACKAGE_REPO.git@main#egg=simple&subdirectory=_packaging/sepypi/pypi/simple

Caching was working when we tried it this way but there some deprecation happening while using  --extra-index-url , so we fixed it using the following:

 pip install -r requirements.txt --extra-index-url https://${{ secrets.ado_token }}@https://github.com

 pip install git+@OUR_INETERNAL_ADO_PACKAGE_REPO.git@main#egg=simple&subdirectory=_packaging/sepypi/pypi/simple

So, we have addressed the following issues while trying to fix the caching problem.
1)Ensured that secrets are correctly referenced using ${{ secrets.ado_token }} in the workflow file to avoid "bad substitution" errors.
2)Used the git+https syntax to install packages directly from the repository.

If these workarounds do not resolve the issue, please provide a link to the build or the public repository to help us further investigate.

**Comment by lmvysakh** [comment]
Hi @screig ,

After investigating, we identified several issues causing the caching to fail, such as secret handling and syntax errors in the pip install command. Initially, the following command was used:
```
pip install -r requirements.txt --extra-index-url https://${ado_token}@OUR_INETERNAL_ADO_PACKAGE_REPO/_packaging/sepypi/pypi/simple/
```
However, this format was invalid for pip install. We made the following fix:
```
pip install -r requirements.txt --extra-index-url https://${{secrets.ado_token}}@OUR_INETERNAL_ADO_PACKAGE_REPO.git@main#egg=simple&subdirectory=_packaging/sepypi/pypi/simple
```
This resolved the caching issue, but there was a deprecation warning with --extra-index-url. To address this, we updated the commands as follows:
```
pip install -r requirements.txt --extra-index-url https://${{ secrets.ado_token }}@https://github.com
pip install git+@OUR_INETERNAL_ADO_PACKAGE_REPO.git@main#egg=simple&subdirectory=_packaging/sepypi/pypi/simple
```
We addressed the following issues to resolve the caching problem:
1. Ensured that secrets are correctly referenced using ${{ secrets.ado_token }} in the workflow file to avoid "bad substitution" errors.
2. Used the git+https syntax to install packages directly from the repository.

If these workarounds do not resolve the issue, please provide a link to the build or the public repository to help us further investigate.

**Comment by screig** [comment]
Hi

The repository I am referencing is provided by Azure and is intended to provide packages (wheels) and is not a code-repository and therefore is not using git.

It looks rather like this

![image](https://github.com/user-attachments/assets/250db4e9-3b3d-4434-b3b7-be5510bda971)

Image from [here](https://blog.tyang.org/2023/01/26/using-azure-artifacts-as-python-pip-package-repository), not mine.

As in this image, the service (Azure Dev Ops / Azure Artifacts) tells me the address to connect to, in order to be able to install packages using pip.

![image](https://github.com/user-attachments/assets/711ce0ae-c713-49a2-a1d2-a793727ad563)

I am not connecting to a git (code) repository where I have the option to use git+https syntax. 

[Here](https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops&tabs=twine) is the azure documentation for the package repo service. I believe across the Microsoft/Github world this is the only service that can provide a python package repo. 

The GitHub Package Registry cannot handle Python package and I think GitHub has [ruled out ](https://github.com/orgs/community/discussions/8542) supporting Python packages in the future through this.

**Comment by lmvysakh** [comment]
Hi @screig,

I'd like to provide some clarity on the caching capabilities supported by the `setup-python` action and its limitations:

The `setup-python` action supports caching for Python packages installed from the public `PyPI`repository. Additionally, if you have a `requirements.txt` file, the action can cache the dependencies listed in it. However, caching may not work seamlessly for packages installed from internal or private repositories, such as Azure Artifacts.

You can find the documentation for the same below:
- [Caching dependencies to speed up workflows](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows)
- [Building and testing Python](https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python)

However, we are suggesting a workaround to access the Azure Artifacts repository by the following:

1. **Create an Azure Artifacts feed** in your Azure DevOps project.
2. **Generate a Personal Access Token (PAT)** with the `Packaging` scope in Azure DevOps.
3. **Store the PAT as a secret** in your GitHub repository (e.g., `AZURE_ARTIFACTS_PAT`).

```python
import os
import subprocess

# Set up the environment variable for the PAT
os.environ['AZURE_ARTIFACTS_PAT'] = 'your_personal_access_token'

# Define the URL for the Azure Artifacts feed
feed_url = "https://pkgs.dev.azure.com/your_organization/your_project/_packaging/your_feed/pypi/simple/"

# Configure pip to use the Azure Artifacts feed
subprocess.run([
    'pip', 'install', '--extra-index-url', f"https://{os.environ['AZURE_ARTIFACTS_PAT']}:@{feed_url}",
    'your_package_name'
], check=True)
```

Here is an example GitHub Actions workflow that sets up Python, configures access to the Azure Artifacts feed, and installs packages:

```yaml
name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies from Azure Artifacts
      env:
        AZURE_ARTIFACTS_PAT: ${{ secrets.AZURE_ARTIFACTS_PAT }}
      run: |
        pip install --upgrade pip
        pip config set global.extra-index-url "https://${AZURE_ARTIFACTS_PAT}:@pkgs.dev.azure.com/your_organization/your_project/_packaging/your_feed/pypi/simple/"
        pip install -r requirements.txt
```

1. Replace placeholders like `your_personal_access_token`, `your_organization`, `your_project`, `your_feed`, and `your_package_name` with your actual details.
2. Ensure that the `AZURE_ARTIFACTS_PAT` secret is properly set in your GitHub repository.

**Comment by screig** [comment]
Hi

I tried this approach of setting the global index url

![Image](https://github.com/user-attachments/assets/de2a757a-d4a7-44b6-a0fd-006b59e5d531)

However I can see no difference

![Image](https://github.com/user-attachments/assets/da4a0a2c-f7f3-4186-b5f8-1a8acd336e7e)

When using the internal package repo the action is still not caching...

![Image](https://github.com/user-attachments/assets/befb6424-c8f2-4911-a6b8-72f29406ffb7)

**Comment by lmvysakh** [comment]
Hi @screig,

Currently, the `setup-python` action does not support caching for external packages, such as `Azure Artifacts`. The caching functionality is primarily designed for packages from the `PyPI` repository and dependencies listed in a `requirements.txt` file.

We recognise the importance of supporting a wider range of repositories and are considering enhancements for future updates. In the meantime, you may need to implement custom caching solutions or use other methods to manage dependencies from `Azure Artifacts`.

Thank you for your understanding. Please feel free to reach out if you have any further concerns or need additional clarification!

**Comment by lmvysakh** [comment]
Hi @screig,

We recommend trying out caching with `actions/cache`, as it can be used to cache Python dependencies. Below is an example workflow demonstrating the same:

```yaml
- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.9'

- name: Cache dependencies
  uses: actions/cache@v4
  with:
    path: ~/.cache/pip
    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    restore-keys: |
      ${{ runner.os }}-pip-

- name: Install dependencies from Azure Artifacts
  env:
    AZURE_ARTIFACTS_PAT: ${{ secrets.AZURE_ARTIFACTS_PAT }}
  run: |
    pip install --upgrade pip
    pip config set global.extra-index-url "https://${AZURE_ARTIFACTS_PAT}:@pkgs.dev.azure.com/your_organization/your_project/_packaging/your_feed/pypi/simple/"
    pip install -r requirements.txt
```

Thank you for your understanding. Please feel free to reach out if you have any further concerns or need additional clarification.

**Comment by lmvysakh** [comment]
Hello @screig,

Just a gentle reminder! Could you please let us know if there are any updates from your side regarding this issue?

Thank you!

**Comment by lmvysakh** [comment]
Hello  @screig,

Just a gentle reminder! Could you please let us know if there are any updates from your side regarding this issue?

Thank you!

**Comment by lmvysakh** [comment]
Hello **@screig**

Due to not receiving a response for a long time, we are going to close this issue for now. Please feel free to reach us in case of any concerns or further clarifications are required to reopen this issue. Thank you!

**Comment by mallman-experian** [comment]
Hi,

We are also interested in caching when using an internal python package repo. Based on my understanding from the conversation, this now sounds more like a feature request than a bug. As such, can it be re-opened as a feature request?

Cheers.

**Comment by mallman-experian** [comment]
I was able to get this working. These are the steps we define in our workflow yaml:

```yaml
    steps:
      - uses: actions/checkout@v4
      - name: Setup virtual environment
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          cache-dependency-path: |
            requirements/base.txt
            requirements/ci.txt
      - run: |
          pip install -r requirements/base.txt
          pip install -r requirements/ci.txt
```

We also set `PIP_EXTRA_INDEX_URL` in the top-level `env` key.

As you can see, we are specifying the requirements files explicitly.

@screig Does this help?

**Comment by lmvysakh** [comment]
Hi @screig ,

We are reopening this issue to look into the requested feature and we will get back to you once we have some feedback on the same.

**Comment by v-aparnajyothi-y** [comment]
Hello, Thanks for raising this request and sharing the context.
We understand the need for caching support when using internal package repositories and agree that it would improve performance and consistency in enterprise workflows.
That said, after reviewing the proposal, we’re not planning to move forward with this enhancement at this time based on the complexity around handling various authentication mechanisms and internal configurations makes this a challenging feature to support reliably.
We’ll continue to monitor interest in this area and revisit the idea if demand increases.
Thank you for your continued engagement and for helping us prioritize improvements. Your feedback is always appreciated!

**Comment by v-aparnajyothi-y** [comment]
Hello Everyone, Please let us know if you have any concerns on the above :)

**Comment by v-aparnajyothi-y** [comment]
Hello Everyone, Please let us know if you have any concerns on the above :)

**Comment by v-aparnajyothi-y** [comment]
Hello Everyone, we are proceeding to close this issue after two reminders as we didn't hear anything from you for a long time. 
Please feel free to reach us in case of any concerns / clarifications required :)
